In [10]:
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_csv("data/Gaming_and_Mental_Health.csv")
df.head()

,record_id,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,...,continued_despite_problems,eye_strain,back_neck_pain,weight_change_kg,exercise_hours_weekly,social_isolation_score,face_to_face_social_hours_weekly,monthly_game_spending_usd,years_gaming,gaming_addiction_risk_level
0,GD0001,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,...,True,True,False,6.8,3.7,7,1.3,383.70,3,Severe
1,GD0002,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,...,False,False,False,0.4,8.5,2,10.7,46.64,1,Low
2,GD0003,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,...,True,False,True,1.8,7.1,5,3.2,100.81,6,Severe
3,GD0004,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,...,False,True,True,0.2,5.2,4,9.1,51.60,7,High
4,GD0005,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,...,False,False,False,0.5,6.1,4,4.5,32.57,1,Moderate

In [4]:
df.shape

(1000, 27)

In [5]:
df.isnull().sum()

record_id                             0
age                                   0
gender                                0
daily_gaming_hours                    0
game_genre                            0
primary_game                          0
gaming_platform                       0
sleep_hours                           0
sleep_quality                         0
sleep_disruption_frequency            0
academic_work_performance             0
grades_gpa                          246
work_productivity_score             326
mood_state                            0
mood_swing_frequency                  0
withdrawal_symptoms                   0
loss_of_other_interests               0
continued_despite_problems            0
eye_strain                            0
back_neck_pain                        0
weight_change_kg                      0
exercise_hours_weekly                 0
social_isolation_score                0
face_to_face_social_hours_weekly      0
monthly_game_spending_usd             0
years_gaming                          0
gaming_addiction_risk_level           0
dtype: int64

In [6]:
df.columns

Index(['record_id', 'age', 'gender', 'daily_gaming_hours', 'game_genre',
       'primary_game', 'gaming_platform', 'sleep_hours', 'sleep_quality',
       'sleep_disruption_frequency', 'academic_work_performance', 'grades_gpa',
       'work_productivity_score', 'mood_state', 'mood_swing_frequency',
       'withdrawal_symptoms', 'loss_of_other_interests',
       'continued_despite_problems', 'eye_strain', 'back_neck_pain',
       'weight_change_kg', 'exercise_hours_weekly', 'social_isolation_score',
       'face_to_face_social_hours_weekly', 'monthly_game_spending_usd',
       'years_gaming', 'gaming_addiction_risk_level'],
      dtype='str')

In [9]:
df1 = df[['age', 'gender', 'daily_gaming_hours', 'game_genre',
       'primary_game', 'gaming_platform', 'sleep_hours', 'sleep_quality',
       'sleep_disruption_frequency', 'face_to_face_social_hours_weekly', 'academic_work_performance']].copy()
df1.head()

,age,gender,daily_gaming_hours,game_genre,primary_game,gaming_platform,sleep_hours,sleep_quality,sleep_disruption_frequency,face_to_face_social_hours_weekly,academic_work_performance
0,17,Male,11.1,Mobile Games,Clash of Clans,PC,3.7,Very Poor,Sometimes,1.3,Below Average
1,21,Male,3.0,MOBA,Dota 2,PC,7.2,Fair,Rarely,10.7,Good
2,23,Male,7.6,FPS,CS:GO,Multi-platform,4.4,Fair,Often,3.2,Poor
3,20,Female,7.2,RPG,Skyrim,Multi-platform,5.1,Fair,Often,9.1,Poor
4,18,Male,6.8,Battle Royale,Apex Legends,PC,3.4,Poor,Never,4.5,Average

In [16]:
df1["game_genre"].unique()

<StringArray>
['Mobile Games', 'MOBA', 'FPS', 'RPG', 'Battle Royale', 'MMO', 'Strategy']
Length: 7, dtype: str

In [17]:
df1["primary_game"].unique()

<StringArray>
[      'Clash of Clans',               'Dota 2',                'CS:GO',
               'Skyrim',         'Apex Legends',         'Call of Duty',
       'Genshin Impact',    'Final Fantasy XIV',         'StarCraft II',
           'Elden Ring',    'League of Legends',              'Warzone',
       'Cyberpunk 2077',                 'PUBG',          'Candy Crush',
    'World of Warcraft',          'PUBG Mobile',       'Mobile Legends',
 'Elder Scrolls Online',             'Valorant',       'Age of Empires',
      'Civilization VI',             'Fortnite',            'Overwatch']
Length: 24, dtype: str

In [13]:
df1.isnull().sum()

age                                 0
gender                              0
daily_gaming_hours                  0
game_genre                          0
primary_game                        0
gaming_platform                     0
sleep_hours                         0
sleep_quality                       0
sleep_disruption_frequency          0
face_to_face_social_hours_weekly    0
academic_work_performance           0
dtype: int64

In [15]:
df1.dtypes

age                                   int64
gender                                  str
daily_gaming_hours                  float64
game_genre                              str
primary_game                            str
gaming_platform                         str
sleep_hours                         float64
sleep_quality                           str
sleep_disruption_frequency              str
face_to_face_social_hours_weekly    float64
academic_work_performance               str
dtype: object

In [12]:
aux_freq = df1.groupby(["game_genre", "academic_work_performance"]).size().reset_index(name="frequencia")

fig = px.bar(
    aux_freq,
    x="game_genre",
    y="frequencia",
    color="academic_work_performance",        # segunda categoria vira cor/grupo
    barmode="group",            # "group" = lado a lado | "stack" = empilhado
    title="Frequência de Performance por tipo de jogo",
    labels={
        "game_genre": "Gênero do jogo",
        "frequencia": "Frequência",
        "academic_work_performance": "Performance na Faculdade e Trabalho"
    },
    text_auto=True
)

fig.show()

In [24]:
fig = px.histogram(
    df1,
    x="age",
    color="academic_work_performance",
    barmode="group"
)
fig.show()

In [25]:
fig = px.scatter(
    df1,
    x="daily_gaming_hours",
    y="sleep_hours",
    color="game_genre",
)

fig.show()